title: "Bryan McEntire"
tagline: "Writer, builder of mythos, observer of the unseen"
description: "Author portal for Bryan McEntire. Explore published works, current projects, and links to Hollow Meridian."

url: "https://bryanmcentire.com"
baseurl: ""

github:
  username: bryanmcentire

social:
  name: Bryan McEntire
  email: you@example.com
  links:
    - https://blackmeridian.org
    - https://swordandpaper.com
    - https://www.linkedin.com/in/bryanmcentire/

theme_mode: dark
